extends: airbnb
parser: babel-eslint
rules:
  comma-dangle: 0
  no-restricted-syntax: 0
  no-underscore-dangle:
    - error
    - allowAfterThis: true
globals:
  $Shape: false
  expect: false
  Generator: false
  Iterable: false
  Iterator: false
  jest: false
  test: false
